name: run daily data download

on:
  schedule:
    - cron: "00 03 * * *"    #runs at 3:00 UTC/11PM EST everyday    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python run_daily.py
      #push
      - name: push files to repo
        run: |
          git config user.name github-actions
          git config user.email "${{secrets.GH_MAIL}}"
          git add -A
          git commit -m "daily update" --allow-empty
          git push
